/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoDatos.*;
import entidades.Vacuna;
import java.time.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author carol
 */
public class CargarVacuna extends javax.swing.JInternalFrame {

    private LocalDate fecha;
    private VacunaData vacdata;
    /**
     * Creates new form CargarVacunas
     */
    public CargarVacuna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTNumSerie = new javax.swing.JTextField();
        jTMarca = new javax.swing.JTextField();
        jTMedida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateCaducidad = new com.toedter.calendar.JDateChooser();
        jBCargar = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        jTNumSerie1 = new javax.swing.JTextField();
        jTMarca1 = new javax.swing.JTextField();
        jTMedida1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateCaducidad1 = new com.toedter.calendar.JDateChooser();
        jBCargar1 = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Carga de vacunas");

        jTNumSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNumSerieKeyTyped(evt);
            }
        });

        jTMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTMarcaKeyTyped(evt);
            }
        });

        jTMedida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTMedidaKeyTyped(evt);
            }
        });

        jLabel2.setText("N° de serie");

        jLabel3.setText("Marca");

        jLabel4.setText("Medida");

        jLabel5.setText("Fecha de caducidad");

        jDateCaducidad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateCaducidadPropertyChange(evt);
            }
        });

        jBCargar.setText("Cargar");
        jBCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCargarActionPerformed(evt);
            }
        });

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setResizable(true);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Carga de vacunas");

        jTNumSerie1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNumSerie1KeyTyped(evt);
            }
        });

        jTMarca1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTMarca1KeyTyped(evt);
            }
        });

        jTMedida1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTMedida1KeyTyped(evt);
            }
        });

        jLabel7.setText("N° de serie");

        jLabel8.setText("Marca");

        jLabel9.setText("Medida");

        jLabel10.setText("Fecha de caducidad");

        jDateCaducidad1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateCaducidad1PropertyChange(evt);
            }
        });

        jBCargar1.setText("Cargar");
        jBCargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCargar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTNumSerie1)
                    .addComponent(jTMarca1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTMedida1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateCaducidad1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNumSerie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTMarca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTMedida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jDateCaducidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCargar1)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTNumSerie)
                    .addComponent(jTMarca, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTMedida, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateCaducidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCargar)
                .addGap(164, 164, 164))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jDateCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jBCargar)
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCargarActionPerformed
       
        VacunaData vd = new VacunaData();      
     
        if(jTNumSerie.getText().isEmpty()||jTMarca.getText().isEmpty()||jTMedida.getText().isEmpty()|| fecha==null){
           JOptionPane.showInternalMessageDialog(this, "Complete todos los campos");
           return;           
        }
        else{
        List <Vacuna> carVacuna = new ArrayList();
            int numSerie = Integer.parseInt(jTNumSerie.getText()); 
            Double medida = Double.parseDouble(jTMedida.getText());
            
            String NroSerieDosis=jTNumSerie.getText();
            String Marca=jTMarca.getText();
            double Medida= medida;
            LocalDate FechaCaduca=fecha;
            Boolean Coloca=false;
            
            Vacuna vacu =new Vacuna(numSerie,Marca,medida,FechaCaduca,Coloca);            
            vd.nuevaVacuna(vacu);

            jTNumSerie.setText(null);
            jTMarca.setText(null);
            jTMedida.setText(null);
            jDateCaducidad.setDate(null);
            
           JOptionPane.showInternalMessageDialog(this, "Vacuna cargada con exito!");

        }
    }//GEN-LAST:event_jBCargarActionPerformed

    private void jDateCaducidadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateCaducidadPropertyChange
        if(jDateCaducidad.getDate()!=null){
        fecha= jDateCaducidad.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        } 
    }//GEN-LAST:event_jDateCaducidadPropertyChange

    private void jTNumSerieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNumSerieKeyTyped

        char c = evt.getKeyChar();
        if(c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_jTNumSerieKeyTyped

    private void jTMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTMarcaKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
            
     if (!(minusculas || mayusculas || espacio))
    {
        evt.consume();
    }
    }//GEN-LAST:event_jTMarcaKeyTyped

    private void jTMedidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTMedidaKeyTyped
        
       int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
            
     if (minusculas || mayusculas || espacio)
    {
        evt.consume();
    }
    }//GEN-LAST:event_jTMedidaKeyTyped

    private void jTNumSerie1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNumSerie1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNumSerie1KeyTyped

    private void jTMarca1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTMarca1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMarca1KeyTyped

    private void jTMedida1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTMedida1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMedida1KeyTyped

    private void jDateCaducidad1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateCaducidad1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateCaducidad1PropertyChange

    private void jBCargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCargar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCargar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCargar;
    private javax.swing.JButton jBCargar1;
    private com.toedter.calendar.JDateChooser jDateCaducidad;
    private com.toedter.calendar.JDateChooser jDateCaducidad1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTMarca;
    private javax.swing.JTextField jTMarca1;
    private javax.swing.JTextField jTMedida;
    private javax.swing.JTextField jTMedida1;
    private javax.swing.JTextField jTNumSerie;
    private javax.swing.JTextField jTNumSerie1;
    // End of variables declaration//GEN-END:variables
}
