/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoDatos.LaboratorioData;
import entidades.Laboratorio;
import javax.swing.JOptionPane;

/**
 *
 * @author carol
 */
public class CargarLaboratorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form CargarLaboratorio
     */
    public CargarLaboratorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFCuit = new javax.swing.JTextField();
        jTFNombreLab = new javax.swing.JTextField();
        jTFPais = new javax.swing.JTextField();
        jTFDomicilio = new javax.swing.JTextField();
        jTFMarca = new javax.swing.JTextField();
        jBCargarLab = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cargar nuevo laboratorio");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CUIT");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("País");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Domicilio");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Marca");

        jTFCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCuitKeyTyped(evt);
            }
        });

        jTFNombreLab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNombreLabKeyTyped(evt);
            }
        });

        jTFPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFPaisKeyTyped(evt);
            }
        });

        jBCargarLab.setBackground(new java.awt.Color(0, 153, 255));
        jBCargarLab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBCargarLab.setForeground(new java.awt.Color(255, 255, 255));
        jBCargarLab.setText("Cargar");
        jBCargarLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCargarLabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFCuit)
                    .addComponent(jTFNombreLab)
                    .addComponent(jTFPais)
                    .addComponent(jTFDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jTFMarca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 120, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCargarLab)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFNombreLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBCargarLab)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFPaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPaisKeyTyped
        if(!(Character.isLetter(evt.getKeyChar()))&&!(Character.isWhitespace(evt.getKeyChar()))){
            evt.consume();
        }
    }//GEN-LAST:event_jTFPaisKeyTyped

    private void jTFNombreLabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreLabKeyTyped
        if(!(Character.isLetter(evt.getKeyChar()))&&!(Character.isWhitespace(evt.getKeyChar()))){
            evt.consume();
        }
    }//GEN-LAST:event_jTFNombreLabKeyTyped

    private void jTFCuitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCuitKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        
        if (!numeros)
        {
            evt.consume();
        }

        
        if (jTFCuit.getText().trim().length() == 10) {
            evt.consume();
            
        }
    }//GEN-LAST:event_jTFCuitKeyTyped

    private void jBCargarLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCargarLabActionPerformed
        try{
            if(jTFCuit.getText().isEmpty()||jTFDomicilio.getText().isEmpty()||jTFMarca.getText().isEmpty()||jTFNombreLab.getText().isEmpty()||jTFPais.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Complete todos los campos");
                return;
            }else{
                if(jTFCuit.getText().length()<10){
                    JOptionPane.showMessageDialog(this, "El CUIT debe tener 10 dígitos");
                    return;
                }
                int cuit=Integer.parseInt(jTFCuit.getText());
                
                String domicilio=jTFDomicilio.getText();
                String marca=jTFMarca.getText();
                String nombre=jTFNombreLab.getText();
                String pais=jTFPais.getText();
                Laboratorio lab=new Laboratorio(cuit,nombre,pais,domicilio,marca);
                LaboratorioData ld=new LaboratorioData();
                ld.nuevoLaboratorio(lab);
                borrarCampos();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Revise que todos sus campos tengan datos correctos");
        }
        
    }//GEN-LAST:event_jBCargarLabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCargarLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTFCuit;
    private javax.swing.JTextField jTFDomicilio;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFNombreLab;
    private javax.swing.JTextField jTFPais;
    // End of variables declaration//GEN-END:variables

    public void borrarCampos(){
        jTFCuit.setText(null);
        jTFDomicilio.setText(null);
        jTFMarca.setText(null);
        jTFNombreLab.setText(null);
        jTFPais.setText(null);
    }
}
