/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoDatos.*;
import Waypoints.Puntero;
import entidades.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author carol
 */
public class CiudadanoTurno extends javax.swing.JInternalFrame {
private Connection con;
private String centroV;
    //private LocalDateTime fechaDeHoy;
    
    /**
     * Creates new form CiudadanoTurno
     */
    public CiudadanoTurno() {
        initComponents();
        cargarCBFdeRiesgo();
        cargarCBTrabajo();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboPatologia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboTrabajo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBSolicitar = new javax.swing.JButton();
        jTNombre = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jTDNI = new javax.swing.JTextField();
        jTTelefono = new javax.swing.JTextField();
        jTEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jMapa = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(512, 466));

        jLabel1.setText("Solicitar turno");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Factor de riesgo");

        jLabel5.setText("Trabajo");

        jLabel6.setText("DNI");

        jLabel7.setText("Teléfono");

        jLabel8.setText("E-Mail");

        jBSolicitar.setText("Solicitar");
        jBSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSolicitarActionPerformed(evt);
            }
        });

        jLabel9.setText("Buscar Centros");

        jMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mapa.png"))); // NOI18N
        jMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMapaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboPatologia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTTelefono)
                                                .addComponent(jTDNI)
                                                .addComponent(jTNombre)
                                                .addComponent(jTApellido)
                                                .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jBSolicitar)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jMapa)
                                        .addGap(34, 34, 34))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addContainerGap(426, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboPatologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 53, Short.MAX_VALUE)
                        .addComponent(jBSolicitar)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jMapa)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSolicitarActionPerformed
        CitaVacunacionData cvd = new CitaVacunacionData();
    
      String sql = "INSERT INTO Ciudadano, citaVacunacion(Ciudadano.nombreCompleto,Ciudadano.dni,Ciudadano.patologia,Ciudadano.ambitoTrabajo,Ciudadano.celular,Ciudadano.email, citaVacunacion.centroVacunacion)"
              + " VALUES(?,?,?,?,?,?,?)";
    
//      int celular = Integer.parseInt(jTDNI.getText());
//      try {
//        PreparedStatement ps = con.prepareStatement(sql);
//        ps.setString(1,jTNombre.getText()+" "+jTApellido.getText());
//        ps.setInt(2, celular);
//        ps.setString(3, (String) jComboPatologia.getSelectedItem());
//        ps.setString(4, (String) jComboTrabajo.getSelectedItem());
//        ps.setString(5, jTTelefono.getText());
//        ps.setString(6, jTEmail.getText());
//    
//        ps.executeUpdate();
//               
//    } catch (SQLException | NullPointerException ex) {
//        JOptionPane.showMessageDialog(this, "Error al acceder a la base de datos");
//    }
//      
        
        if(jTApellido.getText().isEmpty()||jTDNI.getText().isEmpty()||jTEmail.getText().isEmpty()||jTTelefono.getText().isEmpty()){
           JOptionPane.showInternalMessageDialog(this, "Complete todos los campos");
           return;
        }
        ArrayList <CitaVacunacion> citas = new ArrayList();
        citas=cvd.citasPorPersona(Integer.parseInt(jTDNI.getText()));
        if(citas.size()>=1){
            JOptionPane.showMessageDialog(this, "Usted no puede solicitar turno,ya que cuenta con 1 o más dosis");
        }else{
                Puntero p = new Puntero();
            String nombreCompleto=jTNombre.getText()+" "+ jTApellido.getText();
            String email=jTEmail.getText();
            int dni=Integer.parseInt(jTDNI.getText());
            String trabajo=(String)jComboTrabajo.getSelectedItem();
            String patologia=(String)jComboPatologia.getSelectedItem();
            String telefono=jTTelefono.getText();
            String centroVacunatorio=p.getcentroVacunatorio();
            
            
            Ciudadano ciud =new Ciudadano(dni,nombreCompleto,email,telefono,patologia,trabajo);
            CiudadanoData cd=new CiudadanoData();
            cd.guardarCiudadano(ciud);
            LocalDateTime turno;
            if(trabajo.equalsIgnoreCase("OTRO")||patologia.equalsIgnoreCase("NINGUNO")){
                turno=cvd.turnoPara4semanas();
            }else{
                turno=cvd.turnoPara2semanas();
            }
            CitaVacunacion cita=new CitaVacunacion(ciud,1,turno,centroVacunatorio,false);
        }
        
        
    }//GEN-LAST:event_jBSolicitarActionPerformed

    private void jMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMapaActionPerformed
   map m = new map();
   Menuprincipal.escritorio.add(m);
   m.setVisible(true);
   m.moveToFront();
    }//GEN-LAST:event_jMapaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSolicitar;
    private javax.swing.JComboBox<String> jComboPatologia;
    private javax.swing.JComboBox<String> jComboTrabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jMapa;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTDNI;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTTelefono;
    // End of variables declaration//GEN-END:variables

public void cargarCBFdeRiesgo(){
    try{
    jComboPatologia.addItem("--");
    }catch(NullPointerException ex){JOptionPane.showMessageDialog(this,"Ingrese una opción válida");}
    jComboPatologia.addItem("OBESIDAD");
    jComboPatologia.addItem("HIPERTENSIÓN");
    jComboPatologia.addItem("DIABÉTES");
    jComboPatologia.addItem("EPOC");
    jComboPatologia.addItem("MAYOR DE 65 AÑOS");
    jComboPatologia.addItem("NINGUNO");
}

public void cargarCBTrabajo(){
    try{
    jComboTrabajo.addItem("--");
    }catch(NullPointerException ex){JOptionPane.showMessageDialog(this,"Ingrese una opción válida");}
    jComboTrabajo.addItem("SALUD");
    jComboTrabajo.addItem("EDUCACIÓN");
    jComboTrabajo.addItem("SEGURIDAD");
    jComboTrabajo.addItem("COMERCIO");
    jComboTrabajo.addItem("OTRO");
}







}
