
package Vistas;

import AccesoDatos.*;
import entidades.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carol
 */
public class ListarCitas extends javax.swing.JInternalFrame {

    DefaultTableModel modelo=new DefaultTableModel();
    public ListarCitas() {
        initComponents();
        cargarComboBoxMes();
        cargarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRBConcretadas = new javax.swing.JRadioButton();
        jRBVencidas = new javax.swing.JRadioButton();
        jRBCanceladas = new javax.swing.JRadioButton();
        jYCAnio = new com.toedter.calendar.JYearChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaCitas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(800, 400));
        setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione mes");

        jComboBoxMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Citas concretadas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Citas vencidas");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Citas canceladas");

        jRBConcretadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBConcretadasActionPerformed(evt);
            }
        });

        jRBVencidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBVencidasActionPerformed(evt);
            }
        });

        jRBCanceladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCanceladasActionPerformed(evt);
            }
        });

        jTablaCitas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablaCitas);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Seleccione año");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jRBConcretadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRBVencidas)
                .addGap(199, 199, 199)
                .addComponent(jRBCanceladas)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(141, 141, 141)
                .addComponent(jLabel4)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jYCAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5))
                    .addComponent(jYCAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBConcretadas)
                    .addComponent(jRBVencidas)
                    .addComponent(jRBCanceladas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBConcretadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBConcretadasActionPerformed
        jRBVencidas.setSelected(false);
        jRBCanceladas.setSelected(false);
        borrarFilas();
        CitaVacunacionData cvd=new CitaVacunacionData();
        List <CitaVacunacion> citasConcretadas=new ArrayList();
        citasConcretadas=cvd.citasCumplidasPorMes(jComboBoxMes.getSelectedIndex()+1);
        for(CitaVacunacion cv:citasConcretadas){
            if(cv.getFechaHoraCita().getYear()==jYCAnio.getYear()){
               modelo.addRow(new Object[]{cv.getCodigoCita(),cv.getCiudadano().getDni(),cv.getCodRefuerzo(),cv.getFechaHoraCita(),cv.getCentroVacunacion(),cv.getFechaHoraColoca(),cv.getVacuna().getNroSerieDosis(),cv.getCancelar()}); 
            }
            
        }
    }//GEN-LAST:event_jRBConcretadasActionPerformed

    private void jRBVencidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBVencidasActionPerformed
        jRBCanceladas.setSelected(false);
        jRBConcretadas.setSelected(false);
        borrarFilas();
        CitaVacunacionData cvd=new CitaVacunacionData();
        List <CitaVacunacion> citasConcretadas=new ArrayList();
        citasConcretadas=cvd.citasVencidasPorMes(jComboBoxMes.getSelectedIndex()+1);
        for(CitaVacunacion cv:citasConcretadas){
            if(cv.getFechaHoraCita().getYear()==jYCAnio.getYear()){
                modelo.addRow(new Object[]{cv.getCodigoCita(),cv.getCiudadano().getDni(),cv.getCodRefuerzo(),cv.getFechaHoraCita(),cv.getCentroVacunacion(),cv.getFechaHoraColoca(),cv.getVacuna().getNroSerieDosis(),cv.getCancelar()});
            }
            
        }
    }//GEN-LAST:event_jRBVencidasActionPerformed

    private void jRBCanceladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCanceladasActionPerformed
        jRBVencidas.setSelected(false);
        jRBConcretadas.setSelected(false);
        borrarFilas();
        CitaVacunacionData cvd=new CitaVacunacionData();
        List <CitaVacunacion> citasConcretadas=new ArrayList();
        citasConcretadas=cvd.citasCanceladasPorMes(jComboBoxMes.getSelectedIndex()+1);
        for(CitaVacunacion cv:citasConcretadas){
            if(cv.getFechaHoraCita().getYear()==jYCAnio.getYear()){
                modelo.addRow(new Object[]{cv.getCodigoCita(),cv.getCiudadano().getDni(),cv.getCodRefuerzo(),cv.getFechaHoraCita(),cv.getCentroVacunacion(),cv.getFechaHoraColoca(),cv.getVacuna().getNroSerieDosis(),cv.getCancelar()});
            }
            
        }
    }//GEN-LAST:event_jRBCanceladasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRBCanceladas;
    private javax.swing.JRadioButton jRBConcretadas;
    private javax.swing.JRadioButton jRBVencidas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaCitas;
    private com.toedter.calendar.JYearChooser jYCAnio;
    // End of variables declaration//GEN-END:variables

    public void cargarComboBoxMes(){
        jComboBoxMes.addItem("ENERO");
        jComboBoxMes.addItem("FEBRERO");
        jComboBoxMes.addItem("MARZO");
        jComboBoxMes.addItem("ABRIL");
        jComboBoxMes.addItem("MAYO");
        jComboBoxMes.addItem("JUNIO");
        jComboBoxMes.addItem("JULIO");
        jComboBoxMes.addItem("AGOSTO");
        jComboBoxMes.addItem("SEPTIEMBRE");
        jComboBoxMes.addItem("OCTUBRE");
        jComboBoxMes.addItem("NOVIEMBRE");
        jComboBoxMes.addItem("DICIEMBRE");
    }
    
    private void borrarFilas(){
        int f=jTablaCitas.getRowCount()-1;      
        for(;f>=0;f--){
            modelo.removeRow(f);
        }
    }
    
    public void cargarCabecera(){
        modelo.addColumn("Código cita");
        modelo.addColumn("DNI ciudadano");
        modelo.addColumn("Código refuerzo");
        modelo.addColumn("Fecha-hora cita");
        modelo.addColumn("Centro");
        modelo.addColumn("Fecha-hora colocación");
        modelo.addColumn("Dósis");
        modelo.addColumn("Cancelada");
        jTablaCitas.setModel(modelo);
    }
}
