
package Vistas;

import AccesoDatos.*;
import entidades.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carol
 */
public class ListarCitas extends javax.swing.JInternalFrame {

    DefaultTableModel modelo=new DefaultTableModel();
    public ListarCitas() {
        initComponents();
        cargarComboBoxMes();
        cargarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRBConcretadas = new javax.swing.JRadioButton();
        jRBVencidas = new javax.swing.JRadioButton();
        jRBCanceladas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaCitas = new javax.swing.JTable();

        jLabel1.setText("Seleccione mes");

        jLabel2.setText("Citas concretadas");

        jLabel3.setText("Citas vencidas");

        jLabel4.setText("Citas canceladas");

        jRBConcretadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBConcretadasActionPerformed(evt);
            }
        });

        jRBVencidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBVencidasActionPerformed(evt);
            }
        });

        jRBCanceladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCanceladasActionPerformed(evt);
            }
        });

        jTablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaCitas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jRBConcretadas)
                .addGap(111, 111, 111)
                .addComponent(jRBVencidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRBCanceladas)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBConcretadas)
                    .addComponent(jRBVencidas)
                    .addComponent(jRBCanceladas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBConcretadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBConcretadasActionPerformed
        jRBVencidas.setSelected(false);
        jRBCanceladas.setSelected(false);
        borrarFilas();
        CitaVacunacionData cvd=new CitaVacunacionData();
        List <CitaVacunacion> citasConcretadas=new ArrayList();
        citasConcretadas=cvd.citasCumplidasPorMes(jComboBoxMes.getSelectedIndex()+1);
        for(CitaVacunacion cv:citasConcretadas){
            modelo.addRow(new Object[]{cv.getCodigoCita(),cv.getCiudadano().getDni(),cv.getCodRefuerzo(),cv.getFechaHoraCita(),cv.getCentroVacunacion(),cv.getFechaHoraColoca(),cv.getVacuna().getNroSerieDosis(),cv.getCancelar()});
        }
    }//GEN-LAST:event_jRBConcretadasActionPerformed

    private void jRBVencidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBVencidasActionPerformed
        jRBCanceladas.setSelected(false);
        jRBConcretadas.setSelected(false);
        borrarFilas();
        CitaVacunacionData cvd=new CitaVacunacionData();
        List <CitaVacunacion> citasConcretadas=new ArrayList();
        citasConcretadas=cvd.citasVencidasPorMes(jComboBoxMes.getSelectedIndex()+1);
        for(CitaVacunacion cv:citasConcretadas){
            modelo.addRow(new Object[]{cv.getCodigoCita(),cv.getCiudadano().getDni(),cv.getCodRefuerzo(),cv.getFechaHoraCita(),cv.getCentroVacunacion(),cv.getFechaHoraColoca(),cv.getVacuna().getNroSerieDosis(),cv.getCancelar()});
        }
    }//GEN-LAST:event_jRBVencidasActionPerformed

    private void jRBCanceladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCanceladasActionPerformed
        jRBVencidas.setSelected(false);
        jRBConcretadas.setSelected(false);
        borrarFilas();
        CitaVacunacionData cvd=new CitaVacunacionData();
        List <CitaVacunacion> citasConcretadas=new ArrayList();
        citasConcretadas=cvd.citasCanceladasPorMes(jComboBoxMes.getSelectedIndex()+1);
        for(CitaVacunacion cv:citasConcretadas){
            modelo.addRow(new Object[]{cv.getCodigoCita(),cv.getCiudadano().getDni(),cv.getCodRefuerzo(),cv.getFechaHoraCita(),cv.getCentroVacunacion(),cv.getFechaHoraColoca(),cv.getVacuna().getNroSerieDosis(),cv.getCancelar()});
        }
    }//GEN-LAST:event_jRBCanceladasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRBCanceladas;
    private javax.swing.JRadioButton jRBConcretadas;
    private javax.swing.JRadioButton jRBVencidas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaCitas;
    // End of variables declaration//GEN-END:variables

    public void cargarComboBoxMes(){
        jComboBoxMes.addItem("ENERO");
        jComboBoxMes.addItem("FEBRERO");
        jComboBoxMes.addItem("MARZO");
        jComboBoxMes.addItem("ABRIL");
        jComboBoxMes.addItem("MAYO");
        jComboBoxMes.addItem("JUNIO");
        jComboBoxMes.addItem("JULIO");
        jComboBoxMes.addItem("AGOSTO");
        jComboBoxMes.addItem("SEPTIEMBRE");
        jComboBoxMes.addItem("OCTUBRE");
        jComboBoxMes.addItem("NOVIEMBRE");
        jComboBoxMes.addItem("DICIEMBRE");
    }
    
    private void borrarFilas(){
        int f=jTablaCitas.getRowCount()-1;      
        for(;f>=0;f--){
            modelo.removeRow(f);
        }
    }
    
    public void cargarCabecera(){
        modelo.addColumn("Código cita");
        modelo.addColumn("DNI ciudadano");
        modelo.addColumn("Código refuerzo");
        modelo.addColumn("Fecha-hora cita");
        modelo.addColumn("Centro");
        modelo.addColumn("Fecha-hora colocación");
        modelo.addColumn("Dósis");
        modelo.addColumn("Cancelada");
        jTablaCitas.setModel(modelo);
    }
}
