/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author carol
 */
public class MenuCiudadano extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuCiudadano
     */
    public MenuCiudadano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioCiudadano = new javax.swing.JDesktopPane();
        jBConsultarCitas = new javax.swing.JButton();
        jBSolicitarC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        escritorioCiudadano.setPreferredSize(new java.awt.Dimension(512, 466));

        jBConsultarCitas.setText("Consultar citas");
        jBConsultarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarCitasActionPerformed(evt);
            }
        });

        jBSolicitarC.setText("Solicitar cita");
        jBSolicitarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSolicitarCActionPerformed(evt);
            }
        });

        jLabel1.setText("MENU");

        escritorioCiudadano.setLayer(jBConsultarCitas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioCiudadano.setLayer(jBSolicitarC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioCiudadano.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioCiudadanoLayout = new javax.swing.GroupLayout(escritorioCiudadano);
        escritorioCiudadano.setLayout(escritorioCiudadanoLayout);
        escritorioCiudadanoLayout.setHorizontalGroup(
            escritorioCiudadanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioCiudadanoLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(escritorioCiudadanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSolicitarC)
                    .addComponent(jLabel1)
                    .addComponent(jBConsultarCitas))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        escritorioCiudadanoLayout.setVerticalGroup(
            escritorioCiudadanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioCiudadanoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jBSolicitarC)
                .addGap(58, 58, 58)
                .addComponent(jBConsultarCitas)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioCiudadano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioCiudadano, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSolicitarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSolicitarCActionPerformed
        escritorioCiudadano.removeAll();
        escritorioCiudadano.repaint();
        CiudadanoTurno ct= new CiudadanoTurno();
        ct.setVisible(true);
        escritorioCiudadano.add(ct);
        escritorioCiudadano.moveToFront(ct);
        
    }//GEN-LAST:event_jBSolicitarCActionPerformed

    private void jBConsultarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarCitasActionPerformed
        escritorioCiudadano.removeAll();
        escritorioCiudadano.repaint();
        ConsultarCitas cc= new ConsultarCitas();
        cc.setVisible(true);
        escritorioCiudadano.add(cc);
        escritorioCiudadano.moveToFront(cc);
    }//GEN-LAST:event_jBConsultarCitasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorioCiudadano;
    private javax.swing.JButton jBConsultarCitas;
    private javax.swing.JButton jBSolicitarC;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
