/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author carol
 */
public class Menuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menuprincipal
     */
    public Menuprincipal() {
        initComponents();
        jBSolicitarT.setVisible(false);
        jBConsultarC.setVisible(false);
        jBAtras.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/Desktop1.jpg"));
        Image image = icon.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jBASanitario = new javax.swing.JButton();
        jBCiudadano = new javax.swing.JButton();
        jBSolicitarT = new javax.swing.JButton();
        jBConsultarC = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setPreferredSize(new java.awt.Dimension(512, 466));

        jBASanitario.setText("Agente sanitario");
        jBASanitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBASanitarioActionPerformed(evt);
            }
        });

        jBCiudadano.setText("Ciudadano");
        jBCiudadano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCiudadanoActionPerformed(evt);
            }
        });

        jBSolicitarT.setText("Solicitar turno");
        jBSolicitarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSolicitarTActionPerformed(evt);
            }
        });

        jBConsultarC.setText("Consultar citas");
        jBConsultarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarCActionPerformed(evt);
            }
        });

        jBAtras.setText("Atrás");
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });

        escritorio.setLayer(jBASanitario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jBCiudadano, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jBSolicitarT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jBConsultarC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jBAtras, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jBAtras)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jBASanitario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBConsultarC)
                    .addComponent(jBSolicitarT)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jBCiudadano)))
                .addGap(62, 62, 62))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jBAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBASanitario)
                    .addComponent(jBCiudadano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSolicitarT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBConsultarC)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCiudadanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCiudadanoActionPerformed
        
        
        /*escritorio.removeAll();
        escritorio.repaint();
        MenuCiudadano mc= new MenuCiudadano();
        mc.setVisible(true);
        escritorio.add(mc);
        escritorio.moveToFront(mc);*/
        jBCiudadano.setEnabled(false);
        jBSolicitarT.setVisible(true);
        jBConsultarC.setVisible(true);
        jBAtras.setEnabled(true);
        jBASanitario.setVisible(false);
        
    }//GEN-LAST:event_jBCiudadanoActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        if(escritorio.getSelectedFrame()==null){
            jBAtras.setEnabled(false);
            jBCiudadano.setVisible(true);
            jBCiudadano.setEnabled(true);
            jBASanitario.setEnabled(true);
            jBASanitario.setVisible(true);
            jBConsultarC.setVisible(false);
            jBSolicitarT.setVisible(false);
        }
        
        
    }//GEN-LAST:event_jBAtrasActionPerformed

    private void jBSolicitarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSolicitarTActionPerformed
        if(escritorio.getSelectedFrame()==null){
            escritorio.repaint();
            CiudadanoTurno ct= new CiudadanoTurno();
            ct.setVisible(true);
            escritorio.add(ct);
            escritorio.moveToFront(ct);
            escritorio.setSelectedFrame(ct);
        }
        
        
    }//GEN-LAST:event_jBSolicitarTActionPerformed

    private void jBConsultarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarCActionPerformed
        if(escritorio.getSelectedFrame()==null){
            escritorio.repaint();
            ConsultarCitas cc= new ConsultarCitas();
            cc.setVisible(true);
            escritorio.add(cc);
            escritorio.moveToFront(cc);
            escritorio.setSelectedFrame(cc);
        }
        
    }//GEN-LAST:event_jBConsultarCActionPerformed

    private void jBASanitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBASanitarioActionPerformed
        
        try{
            Integer dniAgente=Integer.parseInt(JOptionPane.showInputDialog("Ingrese su DNI"));
            if(dniAgente!=1234){
                JOptionPane.showMessageDialog(this, "El DNI no pertenece a un agente autorizado");
                return;
            }else{
                jBCiudadano.setVisible(false);
                
                jBAtras.setEnabled(true);
                jBASanitario.setEnabled(false);
                
                escritorio.repaint();
                MenuAgenteSanitario mas= new MenuAgenteSanitario();
                mas.setVisible(true);
                escritorio.add(mas);
                escritorio.moveToFront(mas);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Recuerde,el campo solo recibe números y no debe quedar en blanco");
        }
        
    }//GEN-LAST:event_jBASanitarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jBASanitario;
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBCiudadano;
    private javax.swing.JButton jBConsultarC;
    private javax.swing.JButton jBSolicitarT;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
