/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author carol
 */
public class MenuAgenteSanitario extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuAgenteSanitario
     */
    public MenuAgenteSanitario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioASanitario = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jVacunas = new javax.swing.JMenu();
        jMCargarVacunas = new javax.swing.JMenuItem();
        jMListarVacunas = new javax.swing.JMenuItem();
        jCitas = new javax.swing.JMenu();
        jMConfCitas = new javax.swing.JMenuItem();
        jMListarCitas = new javax.swing.JMenuItem();
        jMDosisDiarias = new javax.swing.JMenuItem();
        jMListarVacxCiudadano = new javax.swing.JMenuItem();
        jMPostergarCitaxFaltante = new javax.swing.JMenuItem();
        jLaboratorios = new javax.swing.JMenu();
        jMListarLabs = new javax.swing.JMenuItem();

        setClosable(true);

        javax.swing.GroupLayout escritorioASanitarioLayout = new javax.swing.GroupLayout(escritorioASanitario);
        escritorioASanitario.setLayout(escritorioASanitarioLayout);
        escritorioASanitarioLayout.setHorizontalGroup(
            escritorioASanitarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        escritorioASanitarioLayout.setVerticalGroup(
            escritorioASanitarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        jVacunas.setText("Vacunas");

        jMCargarVacunas.setText("Cargar vacunas");
        jVacunas.add(jMCargarVacunas);

        jMListarVacunas.setText("Listar vacunas según...");
        jVacunas.add(jMListarVacunas);

        jMenuBar1.add(jVacunas);

        jCitas.setText("Citas");

        jMConfCitas.setText("Confirmar citas");
        jMConfCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConfCitasActionPerformed(evt);
            }
        });
        jCitas.add(jMConfCitas);

        jMListarCitas.setText("Listar citas según..");
        jMListarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListarCitasActionPerformed(evt);
            }
        });
        jCitas.add(jMListarCitas);

        jMDosisDiarias.setText("Dosis diarias aplicadas");
        jMDosisDiarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDosisDiariasActionPerformed(evt);
            }
        });
        jCitas.add(jMDosisDiarias);

        jMListarVacxCiudadano.setText("Listar vacuna según ciudadano");
        jCitas.add(jMListarVacxCiudadano);

        jMPostergarCitaxFaltante.setText("Postergar cita por faltante");
        jCitas.add(jMPostergarCitaxFaltante);

        jMenuBar1.add(jCitas);

        jLaboratorios.setText("Laboratorios");

        jMListarLabs.setText("Listar laboratorios");
        jLaboratorios.add(jMListarLabs);

        jMenuBar1.add(jLaboratorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioASanitario)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioASanitario)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMConfCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConfCitasActionPerformed
        escritorioASanitario.repaint();
        ConfirmarCitas cc= new ConfirmarCitas();
        cc.setVisible(true);
        escritorioASanitario.add(cc);
        escritorioASanitario.moveToFront(cc);
    }//GEN-LAST:event_jMConfCitasActionPerformed

    private void jMListarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListarCitasActionPerformed
        escritorioASanitario.repaint();
        ListarCitas lc=new ListarCitas();
        lc.setVisible(true);
        escritorioASanitario.add(lc);
        escritorioASanitario.moveToFront(lc);
    }//GEN-LAST:event_jMListarCitasActionPerformed

    private void jMDosisDiariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDosisDiariasActionPerformed
        escritorioASanitario.repaint();
        DosisDiariasAplicadas dda=new DosisDiariasAplicadas();
        dda.setVisible(true);
        escritorioASanitario.add(dda);
        escritorioASanitario.moveToFront(dda);
    }//GEN-LAST:event_jMDosisDiariasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorioASanitario;
    private javax.swing.JMenu jCitas;
    private javax.swing.JMenu jLaboratorios;
    private javax.swing.JMenuItem jMCargarVacunas;
    private javax.swing.JMenuItem jMConfCitas;
    private javax.swing.JMenuItem jMDosisDiarias;
    private javax.swing.JMenuItem jMListarCitas;
    private javax.swing.JMenuItem jMListarLabs;
    private javax.swing.JMenuItem jMListarVacunas;
    private javax.swing.JMenuItem jMListarVacxCiudadano;
    private javax.swing.JMenuItem jMPostergarCitaxFaltante;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jVacunas;
    // End of variables declaration//GEN-END:variables
}
